import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from typing import Sequence, Union

# Covariant Sequence[float] accepts list[int], list[float], list[floating[Any]],
# np.ndarray, pd.Series, and pd.DataFrame — all of which Pylance can confirm are subtypes.
_NumericArray = Union[Sequence[float], np.ndarray, pd.Series, pd.DataFrame]

def save_sorted_plot(
    y_actual: _NumericArray,
    y_pred: _NumericArray,
    data_name: str,
    folder_name: str,
    model_name_t: str,
    model_name_s: str,
    validate: bool = False
) -> None:
    """
    Generates and saves a line plot comparing actual versus predicted values.
    
    The data points are sorted by the actual target values to provide a monotonic 
    baseline, making it easier to visually assess the model's tracking and variance.
    Automatically adjusts axis limits to include a 10% padding around the data.

    Args:
        y_actual (_NumericArray): The actual ground-truth target values.
        y_pred (_NumericArray): The predicted values generated by the model.
        data_name (str): The name of the dataset, used in the plot title.
        folder_name (str): The directory path where the output plot will be saved.
        model_name_t (str): The formatted model name for the plot title.
        model_name_s (str): The sanitized/unformatted model name for the file name.
        validate (bool, optional): Flag indicating if this is an Out-of-Sample/Validation plot 
            (True = "80-20 Split", False = "In-Sample"). Defaults to False.
            
    Returns:
        None
    """
    # --- Data Preparation ---
    # Combine into a DataFrame and sort by actuals to create a smooth, increasing baseline
    df = pd.DataFrame({'Actual': y_actual, 'Predicted': y_pred})
    df_sorted = df.sort_values(by='Actual')
    
    # --- Axis Calculation & Padding ---
    x_end = df_sorted.shape[0]                                   # Total number of observations
    x = np.arange(0, x_end)                                      # X-axis index values
    
    # Determine the absolute min and max across both actual and predicted series
    y_start = min(df_sorted['Actual'].min(), df_sorted['Predicted'].min())
    y_end = max(df_sorted['Actual'].max(), df_sorted['Predicted'].max())
    y_dist = y_end - y_start
    
    # Expand Y-axis limits by 10% to prevent data points from hugging the plot edges
    y_start = y_start - 0.1 * y_dist
    y_end = y_end + 0.1 * y_dist
    
    # Expand X-axis bounds by 10% (handling potential zero-length edge cases)
    x_end_2 = int(1.1 * x_end) if x_end > 0 else int(0.9 * x_end)
    x_start = int(-0.1 * x_end)

    # --- Plot Generation ---
    plt.figure(figsize=(10, 6))
    plt.plot(x, df_sorted['Predicted'], label='Predicted Values', color='red')
    plt.plot(x, df_sorted['Actual'], color='black', label='Actual Values')
    
    # --- Metadata & Export ---
    split_type = "80-20 Split" if validate else "In-Sample"
    plt.title(f'{data_name} {model_name_t}, {split_type}: Actual (black) vs. Predicted (red)')
    plt.legend()
    plt.ylim(y_start, y_end)
    plt.xlim(x_start, x_end_2)
    
    file_suffix = "80_20" if validate else "In_Sample"
    plt.savefig(f'{folder_name}/{model_name_s}_{file_suffix}.png')
    
    # Clear the current figure to free memory and prevent plot overlap in loops
    plt.close('all')


def save_rsq_plot(
    key: str,
    x: _NumericArray,
    r_sq: _NumericArray,
    adj_r_sq: _NumericArray,
    smape: _NumericArray,
    r_sq_cv: _NumericArray,
    method: str,
    data_name: str,
    folder_name: str,
    model_name_t: str,
    model_name_s: str
) -> None:
    """
    Generates and saves a line plot tracking performance metrics during feature selection.
    
    Visualizes R-squared, Adjusted R-squared, sMAPE, and Cross-Validation R-squared 
    as the number of selected features (n) increases or decreases.

    Args:
        key (str): A specific identifier for the plot/selection direction (e.g., "Forward", "Backward").
        x (_NumericArray): The sequence representing the number of features (X-axis).
        r_sq (_NumericArray): The standard R-squared metric progression.
        adj_r_sq (_NumericArray): The Adjusted R-squared metric progression.
        smape (_NumericArray): The Symmetric Mean Absolute Percentage Error progression.
        r_sq_cv (_NumericArray): The Cross-Validation R-squared metric progression.
        method (str): The feature selection method used (e.g., "Forward Selection").
        data_name (str): The name of the dataset.
        folder_name (str): The directory path where the output plot will be saved.
        model_name_t (str): The formatted model name for the plot title.
        model_name_s (str): The sanitized/unformatted model name for the file name.
        
    Returns:
        None
    """
    # --- Plot Generation ---
    plt.figure(figsize=(10, 6))
    plt.plot(x, r_sq, label='R^2', color='red')
    plt.plot(x, adj_r_sq, label='Adjusted R^2', color='green')
    plt.plot(x, smape, label='sMAPE', color='blue')
    plt.plot(x, r_sq_cv, label='CV R^2', color='black')
    
    # --- Metadata & Export ---
    plt.title(f'R^2 vs n for {model_name_t} {method} on {data_name}')
    plt.legend()
    
    # Note: 'rSq' is hardcoded in the filename to maintain compatibility with downstream scripts
    plt.savefig(f'{folder_name}/{model_name_s}_rSq_{key}.png')
    
    # Clear memory
    plt.close('all')


def save_aic_bic_plot(
    key: str,
    x: _NumericArray,
    aic: _NumericArray,
    bic: _NumericArray,
    method: str,
    data_name: str,
    folder_name: str,
    model_name_t: str,
    model_name_s: str
) -> None:
    """
    Generates and saves a line plot tracking AIC and BIC during feature selection.
    
    Visualizes the Akaike Information Criterion (AIC) and Bayesian Information 
    Criterion (BIC) as the number of selected features changes, helping to assess 
    the trade-off between model fit and complexity.

    Args:
        key (str): A specific identifier for the plot/selection direction (e.g., "Forward", "Backward").
        x (_NumericArray): The sequence representing the number of features (X-axis).
        aic (_NumericArray): The Akaike Information Criterion progression.
        bic (_NumericArray): The Bayesian Information Criterion progression.
        method (str): The feature selection method used (e.g., "Forward Selection").
        data_name (str): The name of the dataset.
        folder_name (str): The directory path where the output plot will be saved.
        model_name_t (str): The formatted model name for the plot title.
        model_name_s (str): The sanitized/unformatted model name for the file name.
        
    Returns:
        None
    """
    # --- Plot Generation ---
    plt.figure(figsize=(10, 6))
    plt.plot(x, aic, label='AIC', color='red')
    plt.plot(x, bic, label='BIC', color='green')
    
    # --- Metadata & Export ---
    plt.title(f'AIC/BIC vs n for {model_name_t} {method} on {data_name}')
    plt.legend()
    
    plt.savefig(f'{folder_name}/{model_name_s}_AIC_BIC_{key}.png')
    
    # Clear memory
    plt.close('all')
