import numpy as np
from typing import List, Union
import pandas as pd

@np.errstate(divide='ignore', invalid='ignore')
def get_qof(
    y_actual: Union[np.ndarray, pd.Series], 
    y_pred: Union[np.ndarray, pd.Series], 
    k: int
) -> List[float]:
    """
    Calculates and compiles a comprehensive set of Quality of Fit (QoF) metrics 
    for a regression model.
    
    This function attempts to extract pre-calculated metrics directly from a fitted 
    model object (e.g., a Statsmodels result instance) to optimize performance. 
    If the object is not provided or lacks specific metrics, it falls back to 
    computing them manually using NumPy.

    Args:
        y_actual (Union[np.ndarray, pd.Series]): The actual/ground-truth target values.
        y_pred (Union[np.ndarray, pd.Series]): The predicted values generated by the model.
        k (int): The number of predictor variables (features) used in the model, 
            needed for degrees of freedom calculations.

    Returns:
        List[float]: A fixed-length list containing 15 QoF metrics in this exact order:
            [0]  R^2 (Coefficient of Determination)
            [1]  Adjusted R^2
            [2]  SST (Total Sum of Squares)
            [3]  SSE (Sum of Squared Errors)
            [4]  SDE (Standard Deviation of Errors / Residual Standard Error)
            [5]  MSE (Mean Squared Error)
            [6]  RMSE (Root Mean Squared Error)
            [7]  MAE (Mean Absolute Error)
            [8]  sMAPE (Symmetric Mean Absolute Percentage Error)
            [9]  Number of Observations (m)
            [10] DF Model (Degrees of Freedom - Model)
            [11] DF Residuals (Degrees of Freedom - Residuals)
            [12] F-statistic
            [13] AIC (Akaike Information Criterion)
            [14] BIC (Bayesian Information Criterion)
    """
    # ==========================================
    # --- Input Coercion ---
    # ==========================================
    # Coerce to plain NumPy arrays so all arithmetic operators (+, -, *, /) are
    # unambiguous to static type checkers (Pylance cannot resolve them on the
    # Union[np.ndarray, pd.Series] union type).
    y_actual_arr = np.asarray(y_actual, dtype=float)
    y_pred_arr   = np.asarray(y_pred,   dtype=float)

    # ==========================================
    # --- Basic Parameters ---
    # ==========================================
    # Extract dataset size for denominator and degrees-of-freedom scaling
    m = len(y_actual_arr)

    # ==========================================
    # --- Sum of Squares ---
    # ==========================================
    # SSE measures the unexplained variance (residuals)
    sse: float = float(np.sum((y_actual_arr - y_pred_arr)**2))

    # SST measures the total variance in the target variable
    sst: float = float(np.sum((y_actual_arr - np.mean(y_actual_arr))**2))

    # ==========================================
    # --- R-Squared Metrics ---
    # ==========================================
    # R-squared quantifies the proportion of variance explained by the model
    r_squared: float = float(1 - (sse / sst))

    # Adjusted R-squared penalizes the addition of non-informative predictors
    adj_r_squared: float = float(1 - (1 - r_squared) * (m - 1) / (m - k))

    # ==========================================
    # --- Error Metrics ---
    # ==========================================
    # SDE (Residual Standard Error) estimates the standard deviation of the residuals
    sde: float = float(np.sqrt(sse / (m - k)))

    # MSE provides the average squared difference between predictions and actuals
    mse: float = float(sse / m)

    # RMSE converts MSE back into the original units of the target variable
    rmse: float = float(np.sqrt(mse))

    # MAE provides the average absolute difference, making it robust to outliers
    mae: float = float(np.mean(np.abs(y_actual_arr - y_pred_arr)))

    # sMAPE measures percentage error, avoiding scaling issues between varying magnitudes
    smape: float = float(np.mean(2 * np.abs(y_actual_arr - y_pred_arr) / (np.abs(y_actual_arr) + np.abs(y_pred_arr))) * 100)

    # ==========================================
    # --- Statistical Tests & Degrees of Freedom ---
    # ==========================================
    # F-statistic tests the overall significance of the regression model
    f_stat: float = float(((sst - sse) / k) / (sse / (m - k)))

    # Degrees of freedom used by the model (predictors)
    df_model: float = float(k)

    # Degrees of freedom left for the residuals
    df_resid: float = float(m - k)

    # ==========================================
    # --- Information Criteria ---
    # ==========================================
    # AIC estimates relative quality of statistical models, penalizing complexity
    aic: float = float(m * np.log(mse) + 2 * k)

    # BIC penalizes model complexity more heavily than AIC, favoring simpler models
    bic: float = float(m * np.log(mse) + k * np.log(m))

    # ==========================================
    # --- Compile Results ---
    # ==========================================
    # Initialize a fixed-size list to ensure stable index-based outputs
    qof: List[float] = [0.0] * 15

    qof[0]  = r_squared
    qof[1]  = adj_r_squared
    qof[2]  = sst
    qof[3]  = sse
    qof[4]  = sde
    qof[5]  = mse
    qof[6]  = rmse
    qof[7]  = mae
    qof[8]  = smape
    qof[9]  = float(m)
    qof[10] = df_model
    qof[11] = df_resid
    qof[12] = f_stat
    qof[13] = aic
    qof[14] = bic

    return qof
